<?php

/**
 * ActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Activity');
    }

	public function getFutureActivityList()
	{
		$today = new DateTime();
		$q = $this->createQuery('a')->where('a.time_from >= "'.date_format($today,'Y-m-d').'" and a.name NOT LIKE \'%[test]%\'')->orderBy('a.time_from ');
		//->leftJoin('a.ActSubject as');

		return $q->execute();
	
	}
	
	public function getOldActivityList()
	{
		$today = new DateTime();
		$q = $this->createQuery('a')->where('a.time_from < "'.date_format($today,'Y-m-d').'" and DATEDIFF( CURDATE(), a.time_from ) <= 30 and a.name NOT LIKE \'%[test]%\'')->orderBy('a.time_from DESC');
		
		
		return $q->execute();
	}
    
	public function getOlderActivityList()
	{
		$today = new DateTime();
		$q = $this->createQuery('a')->where('a.time_from < "'.date_format($today,'Y-m-d').'" and DATEDIFF( CURDATE(), a.time_from ) > 30 and a.name NOT LIKE \'%[test]%\'')->orderBy('a.time_from DESC');
		
		
		return $q->execute();
	}
	
	public function getRelatedActivityList( $currentActId)
	{
		$today = new DateTime();
		$q = $this->createQuery('a')->where('a.time_from >= "'.date_format($today,'Y-m-d').'"and a.id <> '.$currentActId.' and a.name NOT LIKE \'%[test]%\'')->orderBy('a.time_from ')->limit(3);
		
		
		return $q->execute();
	}
	
	public function getComingSoonActivityList()
	{
		$today = new DateTime();
		$q = $this->createQuery('a')->where('a.time_from is NULL  and a.name NOT LIKE \'%[test]%\'')->orderBy('a.updated_at ');
		//->leftJoin('a.ActSubject as');

		return $q->execute();
	
	}
	public function getSendRatingActivityList()
	{
		$today = new DateTime();
		$day = sfConfig::get('app_send_rating_email_delay', '3');
		$q = $this->createQuery('a')->where('DATEDIFF( CURDATE(), a.time_till ) = '.$day.'  ');
		//->leftJoin('a.ActSubject as');

		return $q->execute();
	
	}
	public function getHotActivityList()
	{
		$today = new DateTime();
		$q = $this->createQuery('a')->where('( a.id = 28 or a.id =16 or a.id=21 or a.id=17 or a.id=39 )  and a.name NOT LIKE \'%[test]%\'')->orderBy('a.time_from DESC');
		//->leftJoin('a.ActSubject as');

		return $q->execute();
	
	}
	/*
    public function retrieveById($id)
	{
		$q = $this->createQuery('a')->where('a.id='.$id);

		return $q->fetchOne();
	}
	*/
}