<?php

/**
 * FeeGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    haimeeAct
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FeeGroup extends BaseFeeGroup
{
  //
  public function deleteFees() 
  {
    $fees = $this->getFees();
    foreach( $fees as $fee)
	{
	  $fee->delete();
	}
  }
}