<?php

/**
 * FeeGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeeGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeeGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FeeGroup');
    }
}