<?php

/**
 * FeeTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeeTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeeTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FeeType');
    }
}