<?php

/**
 * UserActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    haimeeAct
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserActivity extends BaseUserActivity
{
	public function getOrderMandatoryFees()
	{
		$q = Doctrine_Query::create()
			->select('f.*')
			->from('Fee f')
			->leftJoin('f.Payment p')
			->where('p.user_activity_id = ?', $this->getId())
			->andWhere('f.fee_type_id = ?', 1);

		return $q->execute();
	}
	
	public function getOrderMandatoryFeesTotal(){
		$mandatoryFeeTotal = 0;
		foreach ($this->getOrderMandatoryFees() as $mandatory_fee){
			$mandatoryFeeTotal += $mandatory_fee->getPrice();
		}
		return $mandatoryFeeTotal;
	}

	public function getOrderOptionalFees()
	{
		$q = Doctrine_Query::create()
			->select('f.*')
			->from('Fee f')
			->leftJoin('f.Payment p')
			->where('p.user_activity_id = ?', $this->getId())
			->andWhere('f.fee_type_id = ?', 2);

		return $q->execute();
	}
	
	public function getOrderOptionalFeesTotal(){
		$UserOptionalFeeTotal = 0;
		foreach ($this->getOrderOptionalFees() as $optional_fee){
			$UserOptionalFeeTotal += $optional_fee->getPrice();
		}
				
		return $UserOptionalFeeTotal;
	}
	
    public function getOrderGroupFees()
	{
		$group_fees = array();
        
		$fees = Doctrine_Query::create()
			->select('f.*')
			->from('Fee f')
			->leftJoin('f.Payment p')
			->where('p.user_activity_id = ?', $this->getId())
			->andWhere('f.fee_type_id = ?', 3)->execute();
        
		foreach($fees as $fee)
		{
			$group_fee['fee_group'] = $fee->getFeeGroup();
            $group_fee['fees'][] = $fee;
			array_push($group_fees, $group_fee);
		}

		return $group_fees;
	}
	
	public function getOrderGroupFeesTotal(){
		$UserGroupFeeTotal = 0;
		foreach ($this->getOrderGroupFees() as $group_fee){
		  foreach ($group_fee['fees'] as $fee){
			  $UserGroupFeeTotal += $fee->getPrice();
		  }
		}
		return $UserGroupFeeTotal;
	}
	
	public function getOrderFeesTotal(){
		return $this->getAmount() * ($this->getOrderMandatoryFeesTotal() + $this->getOrderOptionalFeesTotal() + $this->getOrderGroupFeesTotal());
	}
	
	public function getOrderPayment(Fee $fee)
	{
		$q = Doctrine_Query::create()
			->select('p.*')
			->from('Payment p')
			->where('p.user_activity_id = ?', $this->getId())
			->andWhere('p.fee_id = ?', $fee->getId());

		return $q->fetchOne();
	}

	public function getOrderPaymentOfGroup(FeeGroup $fee_group)
	{
		$q = Doctrine_Query::create()
			->select('p.*')
			->from('Payment p')
			->where('p.user_activity_id = ?', $this->getId())
			->andWhere('p.fee_id in (SELECT f.id FROM Fee f WHERE fee_group_id = ?)', $fee_group->getId());

		return $q->fetchOne();
	}

    public function save(Doctrine_Connection $conn = null)
	{
		if ($this->isNew() && !$this->getEnterTime())
		{
			$this->setEnterTime(date('Y-m-d H:i:s', time()));
		}

		return parent::save($conn);
	}
}