<?php

/**
 * BaseFeeGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $activity_id
 * @property string $name
 * @property string $explanation
 * @property Activity $Activity
 * @property Doctrine_Collection $Fees
 * 
 * @method integer             getActivityId()  Returns the current record's "activity_id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getExplanation() Returns the current record's "explanation" value
 * @method Activity            getActivity()    Returns the current record's "Activity" value
 * @method Doctrine_Collection getFees()        Returns the current record's "Fees" collection
 * @method FeeGroup            setActivityId()  Sets the current record's "activity_id" value
 * @method FeeGroup            setName()        Sets the current record's "name" value
 * @method FeeGroup            setExplanation() Sets the current record's "explanation" value
 * @method FeeGroup            setActivity()    Sets the current record's "Activity" value
 * @method FeeGroup            setFees()        Sets the current record's "Fees" collection
 * 
 * @package    haimeeAct
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeeGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fee_group');
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 2550, array(
             'type' => 'string',
             'length' => 2550,
             ));
        $this->hasColumn('explanation', 'string', 2550, array(
             'type' => 'string',
             'length' => 2550,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Activity', array(
             'local' => 'activity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Fee as Fees', array(
             'local' => 'id',
             'foreign' => 'fee_group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}