<?php

/**
 * BasePaymentType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $UserActivity
 * @property Doctrine_Collection $Payment
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getUserActivity() Returns the current record's "UserActivity" collection
 * @method Doctrine_Collection getPayment()      Returns the current record's "Payment" collection
 * @method PaymentType         setId()           Sets the current record's "id" value
 * @method PaymentType         setName()         Sets the current record's "name" value
 * @method PaymentType         setUserActivity() Sets the current record's "UserActivity" collection
 * @method PaymentType         setPayment()      Sets the current record's "Payment" collection
 * 
 * @package    haimeeAct
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaymentType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('payment_type');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserActivity', array(
             'local' => 'id',
             'foreign' => 'pay_type'));

        $this->hasMany('Payment', array(
             'local' => 'id',
             'foreign' => 'pay_type'));
    }
}