<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $avatar
 * @property boolean $sex
 * @property timestamp $birthday
 * @property string $location
 * @property string $phone
 * @property sfGuardUser $User
 * 
 * @method integer            getUserId()   Returns the current record's "user_id" value
 * @method string             getAvatar()   Returns the current record's "avatar" value
 * @method boolean            getSex()      Returns the current record's "sex" value
 * @method timestamp          getBirthday() Returns the current record's "birthday" value
 * @method string             getLocation() Returns the current record's "location" value
 * @method string             getPhone()    Returns the current record's "phone" value
 * @method sfGuardUser        getUser()     Returns the current record's "User" value
 * @method sfGuardUserProfile setUserId()   Sets the current record's "user_id" value
 * @method sfGuardUserProfile setAvatar()   Sets the current record's "avatar" value
 * @method sfGuardUserProfile setSex()      Sets the current record's "sex" value
 * @method sfGuardUserProfile setBirthday() Sets the current record's "birthday" value
 * @method sfGuardUserProfile setLocation() Sets the current record's "location" value
 * @method sfGuardUserProfile setPhone()    Sets the current record's "phone" value
 * @method sfGuardUserProfile setUser()     Sets the current record's "User" value
 * 
 * @package    haimeeAct
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('avatar', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('sex', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('birthday', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('location', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
		$this->hasColumn('bank_account_info', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}