<?php

/**
 * BaseImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $activity_id
 * @property string $image_location
 * @property Activity $Activity
 * 
 * @method integer  getActivityId()     Returns the current record's "activity_id" value
 * @method string   getImageLocation()  Returns the current record's "image_location" value
 * @method Activity getActivity()       Returns the current record's "Activity" value
 * @method Image    setActivityId()     Sets the current record's "activity_id" value
 * @method Image    setImageLocation()  Sets the current record's "image_location" value
 * @method Image    setActivity()       Sets the current record's "Activity" value
 * 
 * @package    haimeeAct
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image');
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('image_location', 'string', 2550, array(
             'type' => 'string',
             'length' => 2550,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Activity', array(
             'local' => 'activity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}