<?php

/**
 * BaseActSubject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Activities
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getActivities() Returns the current record's "Activities" collection
 * @method ActSubject          setId()         Sets the current record's "id" value
 * @method ActSubject          setName()       Sets the current record's "name" value
 * @method ActSubject          setActivities() Sets the current record's "Activities" collection
 * 
 * @package    haimeeAct
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActSubject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('act_subject');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Activity as Activities', array(
             'local' => 'id',
             'foreign' => 'subject_id'));
    }
}