<?php

/**
 * BasePayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_activity_id
 * @property integer $fee_id
 * @property integer $amount
 * @property timestamp $pay_time
 * @property integer $pay_type
 * @property double $pay_amount
 * @property UserActivity $UserActivity
 * @property Fee $Fee
 * @property PaymentType $PaymentType
 * 
 * @method integer      getUserActivityId()   Returns the current record's "user_activity_id" value
 * @method integer      getFeeId()            Returns the current record's "fee_id" value
 * @method integer      getAmount()           Returns the current record's "amount" value
 * @method timestamp    getPayTime()          Returns the current record's "pay_time" value
 * @method integer      getPayType()          Returns the current record's "pay_type" value
 * @method double       getPayAmount()        Returns the current record's "pay_amount" value
 * @method UserActivity getUserActivity()     Returns the current record's "UserActivity" value
 * @method Fee          getFee()              Returns the current record's "Fee" value
 * @method PaymentType  getPaymentType()      Returns the current record's "PaymentType" value
 * @method Payment      setUserActivityId()   Sets the current record's "user_activity_id" value
 * @method Payment      setFeeId()            Sets the current record's "fee_id" value
 * @method Payment      setAmount()           Sets the current record's "amount" value
 * @method Payment      setPayTime()          Sets the current record's "pay_time" value
 * @method Payment      setPayType()          Sets the current record's "pay_type" value
 * @method Payment      setPayAmount()        Sets the current record's "pay_amount" value
 * @method Payment      setUserActivity()     Sets the current record's "UserActivity" value
 * @method Payment      setFee()              Sets the current record's "Fee" value
 * @method Payment      setPaymentType()      Sets the current record's "PaymentType" value
 * 
 * @package    haimeeAct
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePayment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('payment');
        $this->hasColumn('user_activity_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fee_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pay_time', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('pay_type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pay_amount', 'double', null, array(
             'type' => 'double',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UserActivity', array(
             'local' => 'user_activity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Fee', array(
             'local' => 'fee_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('PaymentType', array(
             'local' => 'pay_type',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}