# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class: sfFileLogger
    param:
      level:   err
      loggers: ~
      file:    %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false


dev:

sendemail:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true
      context:
        host: www.haimee.com
        prefix:
all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true
  storage:
    class: sfSessionStorage
    param:
      session_name: haimeeAct
          
  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  mailer:
   class: sfMailer
   param:
     logging:           %SF_LOGGING_ENABLED%
     charset:           %SF_CHARSET%
     delivery_strategy: realtime
     transport:
       class: Swift_SmtpTransport
       param:
         host:       mail.haimee.com
         port:       26
         encryption: 
         username:   info@haimee.com
         password:   haimee2012
  user:
    class: myUser
    param:
      timeout: 1800